Apps/Inventario/urls.py
__author__ = 'Usuario'
# -*- coding: utf-8 -*-
from django.conf.urls import url

from .views import Familia_Ingresar,Familia_Lista,Familia_Modificar,Familia_Eliminar
from .views import Categoria_Ingresar, Categoria_Lista, Categoria_Modificar,Categoria_Eliminar
from .views import Articulo_Ingresar,Articulo_Modificar, Articulo_Lista, Articulo_Detail,Articulo_Eliminar
from .views import Inventario_Lista

urlpatterns = [
    url(r'^Familia-Ingresar/$', Familia_Ingresar.as_view(), name='Familia_Ingresar'),
    url(r'^Familia-Lista/$', Familia_Lista.as_view(), name='Familia_Lista'),
    url(r'^Familia-Modificar/(?P<pk>[0-9]+)/$', Familia_Modificar.as_view(), name='Familia_Modificar'),
    url(r'^Familia-Eliminar/(?P<pk>[0-9]+)/$', Familia_Eliminar.as_view(), name='Familia_Eliminar'),

    url(r'^Categoria-Ingresar/$', Categoria_Ingresar.as_view(), name='Categoria_Ingresar'),
    url(r'^Categoria-Lista/$', Categoria_Lista.as_view(), name='Categoria_Lista'),
    url(r'^Categoria-Modificar/(?P<pk>[0-9]+)/$', Categoria_Modificar.as_view(), name='Categoria_Modificar'),
    url(r'^Categoria-Eliminar/(?P<pk>[0-9]+)/$', Categoria_Eliminar.as_view(), name='Categoria_Eliminar'),

    url(r'^Articulo-Ingresar/$', Articulo_Ingresar.as_view(), name='Articulo_Ingresar'),
    url(r'^Articulo-Modificar/(?P<pk>[0-9]+)/$', Articulo_Modificar.as_view(), name='Articulo_Modificar'),
    url(r'^Articulo-Lista/$', Articulo_Lista.as_view(), name='Ariculo_Lista'),
    url(r'^Articulo-Detail/(?P<pk>[0-9]+)/$', Articulo_Detail.as_view(), name='Articulo_Detail'),
    url(r'^Articulo-Eliminar/(?P<pk>[0-9]+)/$', Articulo_Eliminar.as_view(), name='Articulo_Eliminar'),

    url(r'^objects/page(?P<page>[0-9]+)/$', Articulo_Lista.as_view()),

    url(r'^Inventario-Lista/$', Inventario_Lista.as_view(), name='Inventario_Lista'),
    url(r'^objects/page(?P<page>[0-9]+)/$', Inventario_Lista.as_view()),


]

Casa_Glamel/urls.py
from django.conf.urls import include, url
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('Apps.Inventario.urls', namespace='Inventario')),
    url(r'^', include('Apps.User.urls', namespace='User_app')),
    url(r'^', include('Apps.GestionInf.urls', namespace='Gestion')),
    url(r'^', include('Apps.ControlProv.urls', namespace='ControlProv')),
    url(r'^', include('Apps.Alquiler.urls', namespace='Alquiler')),
    url(r'^', include('Apps.ControlAdmin.urls', namespace='ControlAdmin')),
    url(r'^', include('Apps.Ventas.urls', namespace='VentasAdmin')),
    url(r'^',include('Apps.Reserva.urls', namespace='Reservas')),
    url(r'^',include('Apps.Egreso.urls', namespace='Egreso')),
    url(r'^',include('Apps.Notificaciones.urls', namespace='Notificaciones')),

]

templates/ModuloAdmin/InventarioTemplate/Categoria/categoria_confirm_delete.html
{% extends "base.html" %}
{% load static from staticfiles %}

{% block title %} Categoria {% endblock%}

{% block link%} <link href="{% static 'css/jquery.datatables.css' %}" rel="stylesheet"> {%endblock%}

{% block user%} {{ user.username }} {% endblock %}

{% block user2 %} {{ user.username }} {% endblock %}

{% block page %} Confirma Eliminar {% endblock %}

{% block page2 %} Confirma Eliminar {% endblock %}

{% block contenido%}
    <div class="col-md-12">
          <form id="basicForm" action="#" class="form-horizontal" method="POST">
          {% csrf_token %}
          <div class="panel panel-default">
              <div class="panel-heading">
                <div class="panel-btns">
                  <a href="#" class="panel-close">&times;</a>
                  <a href="#" class="minimize">&minus;</a>
                </div>
                <h4 class="panel-title">Categoria</h4>
                <p>Bienvenido</p>
              </div>
              <div class="panel-body">
                <div class="form-group">
                  <label class="col-sm-16 control-label">Desea Eliminar la Categoria {{ categoria.nombre }} <span class="asterisk">*</span></label>
                </div>
              </div><!-- panel-body -->
              <div class="panel-footer">
                <div class="row">
                  <div class="col-sm-9 col-sm-offset-3">
                    <button class="btn btn-danger" onclick="this.disabled=true,this.form.submit();">Eliminar</button>
                    <a href="{% url 'Inventario:Categoria_Lista' %}"  class="btn btn-default">volver</a>
                  </div>
                </div>
              </div>
          </div><!-- panel -->
          </form>
    </div>
{% endblock %}

{% block linkscript %}
<script src="{% static 'js/jquery.datatables.min.js'%}"></script>
<script src="{% static 'js/chosen.jquery.min.js'%}"></script>
{% endblock %}

{% block script %} {% endblock %}

templates/ModuloAdmin/InventarioTemplate/Categoria/categoria_form.html
{% extends "base.html" %}
{% load static from staticfiles %}

{% block title %} Crear Categoria {% endblock%}

{% block link%} {%endblock%}

{% block user%} {{ user.username }} {% endblock %}

{% block user2 %} {{ user.username }} {% endblock %}

{% block page %} Ingresar Categoria {% endblock %}

{% block page2 %} Ingresar Categoria {% endblock %}

{% block contenido%}
    <div class="col-md-12">
          <form id="basicForm" action="#" class="form-horizontal" method="POST">
          {% csrf_token %}
          <div class="panel panel-default">
              <div class="panel-heading">
                <div class="panel-btns">
                  <a href="#" class="panel-close">&times;</a>
                  <a href="#" class="minimize">&minus;</a>
                </div>
                <h4 class="panel-title">Categoria</h4>
                <p>Bienvenido, por favor ingrese todos los datos</p>
              </div>
              <div class="panel-body">
                <div class="form-group">
                  <label class="col-sm-3 control-label">Nombre <span class="asterisk">*</span></label>
                  <div class="col-sm-9">
                     {{ form.nombre }}
                  </div>
                </div>
                <div class="form-group">
                  <label class="col-sm-3 control-label">Familia <span class="asterisk">*</span></label>
                  <div class="col-sm-9">
                    {{ form.famila_idfamilia }}
                  </div>
                </div>
                <div class="form-group">
                  <label class="col-sm-3 control-label">Descripcion <span class="asterisk">*</span></label>
                  <div class="col-sm-9">
                    {{ form.descripcion }}
                  </div>
                </div>
              </div><!-- panel-body -->
              <div class="panel-footer">
                <div class="row">
                  <div class="col-sm-9 col-sm-offset-3">
                    <button class="btn btn-primary" onclick="this.disabled=true,this.form.submit();">Guardar</button>
                    <button type="reset" class="btn btn-default">Reset</button>
                  </div>
                </div>
              </div>
            
          </div><!-- panel -->
          </form>
    </div>
{% endblock %}

{% block linkscript %} <script src="{% static 'js/jquery.validate.min.js'%}"></script> {% endblock %}

{% block script %} 

<script>
    jQuery(document).ready(function(){
      
      // Basic Form
      jQuery("#basicForm").validate({
        highlight: function(element) {
          jQuery(element).closest('.form-group').removeClass('has-success').addClass('has-error');
        },
        success: function(element) {
          jQuery(element).closest('.form-group').removeClass('has-error');
        }
      });
      
      
      // Validation with select boxes
      jQuery("#basicForm4").validate({
        highlight: function(element) {
          jQuery(element).closest('.form-group').removeClass('has-success').addClass('has-error');
        },
        success: function(element) {
          jQuery(element).closest('.form-group').removeClass('has-error');
        }
      });
      
      
    });
</script>

{% endblock %}

templates/ModuloAdmin/InventarioTemplate/Categoria/categoria_list.html
{% extends "base.html" %}
{% load static from staticfiles %}

{% block title %} Categoria {% endblock%}

{% block link%} <link href="{% static 'css/jquery.datatables.css' %}" rel="stylesheet"> {%endblock%}

{% block user%} {{ user.username }} {% endblock %}

{% block user2 %} {{ user.username }} {% endblock %}

{% block page %} Categoria {% endblock %}

{% block page2 %} Categoria {% endblock %}

{% block contenido%}
    <div class="panel panel-default">
        <div class="panel-heading">
          <div class="panel-btns">
            <a href="#" class="panel-close">&times;</a>
            <a href="#" class="minimize">&minus;</a>
          </div><!-- panel-btns -->
        </div>
        <div class="panel-body">
          <div class="clearfix mb30"></div>
          <h1 class="subtitle mb5">Categorias</h1>
          <br />
          <div class="table-responsive">
          <table class="table" id="table2">
              <thead>
                 <tr>
                    <th>Nombre</th>
                    <th>Familia</th>
                    <th>Descripcion</th>
                    <th></th>
                 </tr>
              </thead>
              <tbody>
                 {%for categoria in categoria%}
                 <tr class="odd gradeX">
                    <td>{{categoria.nombre}}</td>
                    <td>{{categoria.famila_idfamilia}}</td>
                    <td>{{categoria.descripcion}}</td>
                    <td class="table-action">
                      <a href="{% url 'Inventario:Categoria_Modificar' categoria.pk %}"><i class="fa fa-pencil"></i></a>
                      <a href="{% url 'Inventario:Categoria_Eliminar' categoria.pk %}"><i class="fa fa-trash-o"></i></a>
                    </td>
                 </tr>
                 {%endfor%}
              </tbody>
           </table>
          </div><!-- table-responsive -->

        </div><!-- panel-body -->
      </div><!-- panel -->
{% endblock %}

{% block linkscript %}
<script src="{% static 'js/jquery.datatables.min.js'%}"></script>
<script src="{% static 'js/chosen.jquery.min.js'%}"></script>
{% endblock %}

{% block script %}
<script>
  jQuery(document).ready(function() {

    jQuery('#table1').dataTable();

    jQuery('#table2').dataTable({
      "sPaginationType": "full_numbers"
    });

    // Chosen Select
    jQuery("select").chosen({
      'min-width': '100px',
      'white-space': 'nowrap',
      disable_search_threshold: 10
    });

    // Delete row in a table
    jQuery('.delete-row').click(function(){
      var c = confirm("Continue delete?");
      if(c)
        jQuery(this).closest('tr').fadeOut(function(){
          jQuery(this).remove();
        });

        return false;
    });

    // Show aciton upon row hover
    jQuery('.table-hidaction tbody tr').hover(function(){
      jQuery(this).find('.table-action-hide a').animate({opacity: 1});
    },function(){
      jQuery(this).find('.table-action-hide a').animate({opacity: 0});
    });
  });
</script>

{% endblock %}