Apps/Egreso/urls.py
from django.conf.urls import url
from .views import Egreso_Ingresar,Egreso_Delete,Egreso_Modificar,Egreso_List

urlpatterns = [
    url(r'^Egreso-Ingresar/$', Egreso_Ingresar.as_view(), name='Egreso_Ingresar'),
    url(r'^Egreso-List/$', Egreso_List.as_view(), name='Egreso_List'),
    url(r'^Egreso-Modificar/(?P<pk>[0-9]+)/$', Egreso_Modificar.as_view(), name='Egreso_Modificar'),
    url(r'^Egreso-Delete/(?P<pk>[0-9]+)/$', Egreso_Delete.as_view(), name='Egreso_Delete'),
]

Apps/Notificaciones/urls.py
from django.conf.urls import url
from .views import Notificaciones_Ingresar,Notificaciones_List,Notificaciones_Modificar,Notificaciones_Delete


urlpatterns = [
    url(r'^Notificaciones-Ingresar/$', Notificaciones_Ingresar.as_view(), name='Notificaciones_Ingresar'),
    url(r'^Notificaciones-List/$', Notificaciones_List.as_view(), name='Notificaciones_List'),
    url(r'^Notificaciones-Modificar/(?P<pk>[0-9]+)/$', Notificaciones_Modificar.as_view(), name='Notificaciones_Modificar'),
    url(r'^Notificaciones-Delete/(?P<pk>[0-9]+)/$', Notificaciones_Delete.as_view(), name='Notificaciones_Delete'),
]

Casa_Glamel/urls.py
from django.conf.urls import include, url
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('Apps.Inventario.urls', namespace='Inventario')),
    url(r'^', include('Apps.User.urls', namespace='User_app')),
    url(r'^', include('Apps.GestionInf.urls', namespace='Gestion')),
    url(r'^', include('Apps.ControlProv.urls', namespace='ControlProv')),
    url(r'^', include('Apps.Alquiler.urls', namespace='Alquiler')),
    url(r'^', include('Apps.ControlAdmin.urls', namespace='ControlAdmin')),
    url(r'^', include('Apps.Ventas.urls', namespace='VentasAdmin')),
    url(r'^',include('Apps.Reserva.urls', namespace='Reservas')),
    url(r'^',include('Apps.Egreso.urls', namespace='Egreso')),
    url(r'^',include('Apps.Notificaciones.urls', namespace='Notificaciones')),

]

Apps/Egreso/models.py
# -*- coding: utf-8 -*-
from django.db import models

class Egreso(models.Model):
    fecha = models.DateField()
    asunto = models.CharField(max_length=100)
    valor = models.IntegerField()

    def __str__(self):
        return self.asunto

Apps/Egreso/forms.py
from django import forms

from .models import Egreso

class Egreso_Form(forms.ModelForm):

    class Meta:
        model = Egreso
        fields = ['fecha','asunto','valor']
        widgets = {
            'asunto':forms.TextInput(attrs = {
                'type':'text',
                'name':'asunto',
                'class':'form-control',
                'placeholder':'Ingrese el Asunto',
                'required':True
            }),
            'valor':forms.TextInput(attrs = {
                'type':'text',
                'name':'valor',
                'class':'form-control',
                'placeholder':'Ingrese el valor',
                'required':True
            }),
            'fecha': forms.DateInput(attrs={
                'type':'text',
                'class':'form-control',
                'name':'fecha_devolucion',
                'placeholder':'Ingrese Fecha ',
                'id':'prueba2'
            }),
        }

Apps/Egreso/views.py
from django.views.generic.edit import CreateView,DeleteView,UpdateView
from django.views.generic import ListView
from braces.views import LoginRequiredMixin,SuperuserRequiredMixin
from django.core.urlresolvers import reverse_lazy


from .models import Egreso
from .forms import Egreso_Form

class Egreso_Ingresar(LoginRequiredMixin,CreateView):
    model = Egreso
    template_name = 'ModuloRecepcionista/Otros/Egresos/egreso_form.html'
    form_class = Egreso_Form
    login_url = '/'
    success_url = reverse_lazy('Egreso:Egreso_Ingresar')


class Egreso_Modificar(LoginRequiredMixin,SuperuserRequiredMixin,UpdateView):
    model = Egreso
    login_url = '/'
    template_name = u'ModuloAdmin/Otros/Egresos/egresos_form.html'
    form_class = Egreso_Form
    success_url = reverse_lazy('Egreso:Egreso_List')


class Egreso_List(LoginRequiredMixin,SuperuserRequiredMixin,ListView):
    model = Egreso
    login_url = '/'
    template_name = u'ModuloAdmin/Otros/Egresos/egresos_list.html'
    context_object_name = 'egreso'


class Egreso_Delete(LoginRequiredMixin,SuperuserRequiredMixin,DeleteView):
    model = Egreso
    login_url = '/'
    context_object_name = 'egreso'
    template_name = u'ModuloAdmin/Otros/Egresos/egresos_comfirm_delete.html'
    success_url = reverse_lazy('Egreso:Egreso_List')

templates/ModuloAdmin/Otros/Egresos/egresos_comfirm_delete.html
{% extends "base.html" %}
{% load static from staticfiles %}

{% block title %} Egresos {% endblock%}

{% block link%} <link href="{% static 'css/jquery.datatables.css' %}" rel="stylesheet"> {%endblock%}

{% block user%} {{ user.username }} {% endblock %}

{% block user2 %} {{ user.username }} {% endblock %}

{% block page %} Confirma Eliminar {% endblock %}

{% block page2 %} Confirma Eliminar {% endblock %}

{% block contenido%}
    <div class="col-md-12">
          <form id="basicForm" action="#" class="form-horizontal" method="POST">
          {% csrf_token %}
          <div class="panel panel-default">
              <div class="panel-heading">
                <div class="panel-btns">
                  <a href="#" class="panel-close">&times;</a>
                  <a href="#" class="minimize">&minus;</a>
                </div>
                <h4 class="panel-title">Egresos</h4>
                <p>Bienvenido</p>
              </div>
              <div class="panel-body">
                <div class="form-group">
                  <label class="col-sm-16 control-label">Desea Eliminar la egreso{{ egreso.asunto }} <span class="asterisk">*</span></label>
                </div>
              </div><!-- panel-body -->
              <div class="panel-footer">
                <div class="row">
                  <div class="col-sm-9 col-sm-offset-3">
                    <button type="submit" class="btn btn-danger" onclick="this.disabled=true,this.form.submit();">Eliminar</button>
                    <a href="{% url 'Notificaciones:Notificaciones_List' %}"  class="btn btn-default">volver</a>
                  </div>
                </div>
              </div>
          </div><!-- panel -->
          </form>
    </div>
{% endblock %}

{% block linkscript %}
<script src="{% static 'js/jquery.datatables.min.js'%}"></script>
<script src="{% static 'js/chosen.jquery.min.js'%}"></script>
{% endblock %}

{% block script %} {% endblock %}

templates/ModuloAdmin/Otros/Egresos/egresos_form.html
{% extends "base.html" %}
{% load static from staticfiles %}

{% block title %} Egresos {% endblock%}

{% block link%} {%endblock%}

{% block user%} {{ user.username }}{% endblock %}

{% block user2 %} {{ user.username }}{% endblock %}

{% block page %} Ingresar Egreso {% endblock %}

{% block page2 %} Ingresar Egreso {% endblock %}

{% block contenido%}
    <div class="col-md-12">
          <form id="basicForm" action="#" class="form-horizontal" method="POST">
          {% csrf_token %}
          <div class="panel panel-default">
              <div class="panel-heading">
                <div class="panel-btns">
                  <a href="#" class="panel-close">&times;</a>
                  <a href="#" class="minimize">&minus;</a>
                </div>
                <h4 class="panel-title">Egresos</h4>
                <p>Bienvenido, por favor ingrese todos los datos</p>
              </div>
              <div class="panel-body">
                  <div class="form-group">
                  <label class="col-sm-3 control-label">Fecha<span class="asterisk">*</span></label>
                  <div class="col-sm-9">
                    {{ form.fecha }}
                  </div>
                </div>
                <div class="form-group">
                  <label class="col-sm-3 control-label">Asunto<span class="asterisk">*</span></label>
                  <div class="col-sm-9">
                    {{ form.asunto }}
                  </div>
                </div>
                <div class="form-group">
                  <label class="col-sm-3 control-label">Valor <span class="asterisk">*</span></label>
                  <div class="col-sm-9">
                    {{ form.valor }}
                  </div>
                </div>
              </div><!-- panel-body -->
              <div class="panel-footer">
                <div class="row">
                  <div class="col-sm-9 col-sm-offset-3">
                    <button class="btn btn-primary" onclick="this.disabled=true,this.form.submit();">Guardar</button>
                    <button type="reset" class="btn btn-default">Reset</button>
                  </div>
                </div>
              </div><!-- panel -->
          </form>
    </div>
{% endblock %}



{% block linkscript %}<script src="{% static 'js/jquery.validate.min.js' %}"></script>
    <script src="{% static 'js/jquery-ui-1.10.3.min.js' %}"></script>
    <script src="{% static 'js/chosen.jquery.min.js' %}"></script>
{% endblock %}

{% block script %}
<script>
    jQuery(document).ready(function(){

      // Basic Form
      jQuery("#basicForm").validate({
        highlight: function(element) {
          jQuery(element).closest('.form-group').removeClass('has-success').addClass('has-error');
        },
        success: function(element) {
          jQuery(element).closest('.form-group').removeClass('has-error');
        }
      });


      // Validation with select boxes
      jQuery("#basicForm4").validate({
        highlight: function(element) {
          jQuery(element).closest('.form-group').removeClass('has-success').addClass('has-error');
        },
        success: function(element) {
          jQuery(element).closest('.form-group').removeClass('has-error');
        }
      });

        jQuery("#prueba").datepicker({dateFormat: 'dd/mm/yy'});
        jQuery('#prueba2').datepicker({dateFormat: 'dd/mm/yy'});

    });
    </script>
{% endblock %}

templates/ModuloAdmin/Otros/Egresos/egresos_list.html
{% extends "base.html" %}
{% load static from staticfiles %}

{% block title %} Egresos {% endblock%}

{% block link%} <link href="{% static 'css/jquery.datatables.css' %}" rel="stylesheet"> {%endblock%}

{% block user%} {{ user.username }} {% endblock %}

{% block user2 %} {{ user.username }} {% endblock %}

{% block page %} Listado de  Egreso {% endblock %}

{% block page2 %} Listado de Egreso {% endblock %}

{% block contenido%}
    <div class="panel panel-default">
        <div class="panel-heading">
          <div class="panel-btns">
            <a href="#" class="panel-close">&times;</a>
            <a href="#" class="minimize">&minus;</a>
          </div><!-- panel-btns -->
        </div>
        <div class="panel-body">
          <div class="clearfix mb30"></div>
          <h1 class="subtitle mb5">Egresos</h1>
          <br />
          <div class="table-responsive">
          <table class="table" id="table2">
              <thead>
                 <tr>
                    <th>Fecha</th>
                    <th>Asunto</th>
                    <th>Valor</th>
                    <th></th>
                 </tr>
              </thead>
              <tbody>
                 {%for egreso in egreso%}
                 <tr class="odd gradeX">
                    <td>{{egreso.fecha}}</td>
                    <td>{{egreso.asunto}}</td>
                    <td>{{egreso.valor}}</td>
                    <td class="table-action">
                      <a href="{% url 'Egreso:Egreso_Modificar' egreso.pk %}"><i class="fa fa-pencil"></i></a>
                      <a href="{% url 'Egreso:Egreso_Delete' egreso.pk %}"><i class="fa fa-trash-o"></i></a>
                    </td>
                 </tr>
                 {%endfor%}
              </tbody>
           </table>
          </div><!-- table-responsive -->
          
        </div><!-- panel-body -->
      </div><!-- panel -->
{% endblock %}

{% block linkscript %} 
<script src="{% static 'js/jquery.datatables.min.js'%}"></script> 
<script src="{% static 'js/chosen.jquery.min.js'%}"></script>
{% endblock %}

{% block script %} 
<script>
  jQuery(document).ready(function() {
    
    jQuery('#table1').dataTable();
    
    jQuery('#table2').dataTable({
      "sPaginationType": "full_numbers"
    });
    
    // Chosen Select
    jQuery("select").chosen({
      'min-width': '100px',
      'white-space': 'nowrap',
      disable_search_threshold: 10
    });
    
    // Delete row in a table
    jQuery('.delete-row').click(function(){
      var c = confirm("Continue delete?");
      if(c)
        jQuery(this).closest('tr').fadeOut(function(){
          jQuery(this).remove();
        });
        
        return false;
    });
    
    // Show aciton upon row hover
    jQuery('.table-hidaction tbody tr').hover(function(){
      jQuery(this).find('.table-action-hide a').animate({opacity: 1});
    },function(){
      jQuery(this).find('.table-action-hide a').animate({opacity: 0});
    });
  });
</script>

{% endblock %}