Apps/GestionInf/urls.py
from django.conf.urls import url

from .views import Proveedor_Ingresar,Proveedor_Lista,Proveedor_Modificar,Proveedor_Eliminar
from .views import Cliente_Ingresar,Cliente_Modificar,Cliente_Eliminar,Cliente_Lista

urlpatterns = [
    url(r'^Proveedor-Ingresar/$', Proveedor_Ingresar.as_view(), name='Proveedor_Ingresar'),
    url(r'^Proveedor-Lista/$', Proveedor_Lista.as_view(), name='Proveedor_Lista'),
    url(r'^Proveedor-Modificar/(?P<pk>[0-9]+)/$', Proveedor_Modificar.as_view(), name='Proveedor_Modificar'),
    url(r'^Proveedor-Eliminar/(?P<pk>[0-9]+)/$', Proveedor_Eliminar.as_view(), name='Proveedor_Eliminar'),

    url(r'^Cliente-Ingresar/$', Cliente_Ingresar.as_view(), name='Cliente_Ingresar'),
    url(r'^Cliente-Lista/$', Cliente_Lista.as_view(), name='Cliente_Lista'),
    url(r'^Cliente-Modificar/(?P<pk>[0-9]+)/$', Cliente_Modificar.as_view(), name='Cliente_Modificar'),
    url(r'^Cliente-Eliminar/(?P<pk>[0-9]+)/$', Cliente_Eliminar.as_view(), name='Cliente_Eliminar'),
]

Casa_Glamel/urls.py
from django.conf.urls import include, url
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('Apps.Inventario.urls', namespace='Inventario')),
    url(r'^', include('Apps.User.urls', namespace='User_app')),
    url(r'^', include('Apps.GestionInf.urls', namespace='Gestion')),
    url(r'^', include('Apps.ControlProv.urls', namespace='ControlProv')),
    url(r'^', include('Apps.Alquiler.urls', namespace='Alquiler')),
    url(r'^', include('Apps.ControlAdmin.urls', namespace='ControlAdmin')),
    url(r'^', include('Apps.Ventas.urls', namespace='VentasAdmin')),
    url(r'^',include('Apps.Reserva.urls', namespace='Reservas')),
    url(r'^',include('Apps.Egreso.urls', namespace='Egreso')),
    url(r'^',include('Apps.Notificaciones.urls', namespace='Notificaciones')),

]

templates/ModuloRecepcionista/Cliente/cliente_confirm_delete.html
{% extends "base_2.html" %}
{% load static from staticfiles %}

{% block title %} Eliminar Cliente {% endblock%}

{% block link%} <link href="{% static 'css/jquery.datatables.css' %}" rel="stylesheet"> {%endblock%}

{% block user%} {{ user.username }} {% endblock %}

{% block user2 %} {{ user.username }} {% endblock %}

{% block page %} Confirma Eliminar {% endblock %}

{% block page2 %} Confirma Eliminar {% endblock %}

{% block contenido%}
    <div class="col-md-12">
          <form id="basicForm" action="#" class="form-horizontal" method="POST">
          {% csrf_token %}
          <div class="panel panel-default">
              <div class="panel-heading">
                <div class="panel-btns">
                  <a href="#" class="panel-close">&times;</a>
                  <a href="#" class="minimize">&minus;</a>
                </div>
                <h4 class="panel-title">Cliente</h4>
                <p>Bienvenido</p>
              </div>
              <div class="panel-body">
                <div class="form-group">
                  <label class="col-sm-16 control-label">Desea Eliminar El proveedor {{ cliente.full_nombre }} <span class="asterisk">*</span></label>
                </div>
              </div><!-- panel-body -->
              <div class="panel-footer">
                <div class="row">
                  <div class="col-sm-9 col-sm-offset-3">
                    <button class="btn btn-danger" onclick="this.disabled=true,this.form.submit();">Eliminar</button>
                    <a href="{% url 'Gestion:Cliente_Lista' %}"  class="btn btn-default">volver</a>
                  </div>
                </div>
              </div>
          </div><!-- panel -->
          </form>
    </div>
{% endblock %}

{% block linkscript %}
<script src="{% static 'js/jquery.datatables.min.js'%}"></script>
<script src="{% static 'js/chosen.jquery.min.js'%}"></script>
{% endblock %}

{% block script %} {% endblock %}

templates/ModuloRecepcionista/Cliente/cliente_form.html
{% extends "base_2.html" %}
{% load static from staticfiles %}

{% block title %} Cliente {% endblock%}

{% block link%} {%endblock%}

{% block user%} {{ user.username }}{% endblock %}

{% block user2 %} {{ user.username }}{% endblock %}

{% block page %} Ingresar Cliente {% endblock %}

{% block page2 %} Ingresar Cliente {% endblock %}

{% block contenido%}
    <div class="col-md-12">
          <form id="basicForm" action="#" class="form-horizontal" method="POST">
          {% csrf_token %}
          <div class="panel panel-default">
              <div class="panel-heading">
                <div class="panel-btns">
                  <a href="#" class="panel-close">&times;</a>
                  <a href="#" class="minimize">&minus;</a>
                </div>
                <h4 class="panel-title">Cliente</h4>
                <p>Bienvenido, por favor ingrese todos los datos</p>
              </div>
              <div class="panel-body">
                <div class="form-group">
                  <label class="col-sm-3 control-label">Nombre<span class="asterisk">*</span></label>
                  <div class="col-sm-9">
                    {{ form.full_nombre }}
                  </div>
                </div>
                <div class="form-group">
                  <label class="col-sm-3 control-label">Identificacion <span class="asterisk">*</span></label>
                  <div class="col-sm-9">
                    {{ form.identificacion }}
                  </div>
                </div>
                <div class="form-group">
                  <label class="col-sm-3 control-label">Direccion <span class="asterisk">*</span></label>
                  <div class="col-sm-9">
                    {{ form.direccion }}
                  </div>
                </div>
                <div class="form-group">
                  <label class="col-sm-3 control-label">Telefono <span class="asterisk">*</span></label>
                  <div class="col-sm-9">
                    {{ form.telefono }}
                  </div>
                </div>
                <div class="form-group">
                  <label class="col-sm-3 control-label">Correo <span class="asterisk">*</span></label>
                  <div class="col-sm-9">
                    {{ form.correo }}
                  </div>
                </div>
                  <div class="form-group">
                  <label class="col-sm-3 control-label">Numero de Compras <span class="asterisk">*</span></label>
                  <div class="col-sm-9">
                    {{ form.numeros_compras }}
                  </div>
                </div>
                  <div class="form-group">
                  <label class="col-sm-3 control-label">Peligroso <span class="asterisk">*</span></label>
                  <div class="col-sm-9">
                    {{ form.peligroso }}
                  </div>
                </div>
              </div><!-- panel-body -->
              <div class="panel-footer">
                <div class="row">
                  <div class="col-sm-9 col-sm-offset-3">
                    <button class="btn btn-primary" onclick="this.disabled=true,this.form.submit();">Guardar</button>
                    <button type="reset" class="btn btn-default">Reset</button>
                  </div>
                </div>
          </div><!-- panel -->
          </form>
    </div>
{% endblock %}

{% block linkscript %}<script src="{% static 'js/jquery.validate.min.js'%}"></script> {% endblock %}

{% block script %}
<script>
    jQuery(document).ready(function(){

      // Basic Form
      jQuery("#basicForm").validate({
        highlight: function(element) {
          jQuery(element).closest('.form-group').removeClass('has-success').addClass('has-error');
        },
        success: function(element) {
          jQuery(element).closest('.form-group').removeClass('has-error');
        }
      });


      // Validation with select boxes
      jQuery("#basicForm4").validate({
        highlight: function(element) {
          jQuery(element).closest('.form-group').removeClass('has-success').addClass('has-error');
        },
        success: function(element) {
          jQuery(element).closest('.form-group').removeClass('has-error');
        }
      });


    });
    </script>
{% endblock %}

templates/ModuloRecepcionista/Cliente/cliente_list.html
{% extends "base_2.html" %}
{% load static from staticfiles %}

{% block title %}  Cliente {% endblock%}

{% block link%} <link href="{% static 'css/jquery.datatables.css' %}" rel="stylesheet"> {%endblock%}

{% block user%} {{ user.username }} {% endblock %}

{% block user2 %} {{ user.username }} {% endblock %}

{% block page %} Cliente Lista {% endblock %}

{% block page2 %} Cliente Lista {% endblock %}

{% block contenido%}
    <div class="contentpanel">

      <div class="mb30"></div>

      <div class="people-list">
        <div class="row">
            {% for cliente in cliente %}
          <div class="col-md-6">
            <div class="people-item">
              <div class="media">
                <div class="media-body">
                  <h4 class="person-name">{{ cliente.full_nombre }}
                      {% if cliente.peligroso %}
                          <span class="label label-danger"><span class="glyphicon glyphicon-thumbs-down"></span></span>
                      {% else %}
                          <span class="label label-success"><span class="glyphicon glyphicon-thumbs-up"></span></span>
                      {% endif %}</h4>
                    <div class="text-muted"><i class="fa fa-male"></i> {{ cliente.identificacion }}</div>
                  <div class="text-muted"><i class="fa fa-map-marker"></i> {{ cliente.direccion }}</div>
                  <div class="text-muted"><i class="fa  fa-phone"></i> {{ cliente.telefono }} </div>
                  <div class="text-muted"><i class="fa fa-envelope-o"></i> {{ cliente.correo }} </div>
                  <ul class="social-list">
                    <li><a href="{% url 'Gestion:Cliente_Modificar' cliente.pk %}" class="tooltips" data-toggle="tooltip" data-placement="top" title=Modificar"><i class="fa fa-pencil"></i></a></li>
                    <li><a href="{% url 'Gestion:Cliente_Eliminar' cliente.pk %}" class="tooltips" data-toggle="tooltip" data-placement="top" title="Eliminar"><i class="fa fa-trash-o"></i></a></li>
                  </ul>
                </div>
              </div>
            </div>
          </div><!-- col-md-6 -->
        {% endfor %}
        </div><!-- row -->
      </div><!-- people-list -->

    </div><!-- contentpanel -->

{% endblock %}

{% block linkscript %}
<script src="{% static 'js/jquery.datatables.min.js'%}"></script>
<script src="{% static 'js/chosen.jquery.min.js'%}"></script>
{% endblock %}

{% block script %} {% endblock %}