Apps/ControlProv/urls.py
from django.conf.urls import url

from .views import Factura_Proveedor_Ingresar,Pedido_Ingresar,Factura_Proveedor_Lista,Factura_Proveedor_Detail
from .views import Factura_Proveedor_Detail_Imprimir
from .views import Pedido_Eliminar,Factura_Eliminar,Factura_Modificar

urlpatterns = [
    url(r'^Registro-Pedido/$', Factura_Proveedor_Ingresar.as_view(), name='Factura_Proveedor_Ingresar'),
    url(r'^Registro-Pedido/(?P<pk>[0-9]+)/$', Pedido_Ingresar.as_view(), name='Pedido_Ingresar'),
    url(r'^Factura-Proveedor-Lista/$', Factura_Proveedor_Lista.as_view(), name='Factura_Proveedor_Lista'),
    url(r'^Factura-Proveedor-Detail/(?P<pk>[0-9]+)/$', Factura_Proveedor_Detail.as_view(), name='Factura_Proveedor_Detail'),
    url(r'^Factura-Proveedor-Detail-Imprimir/(?P<pk>[0-9]+)/$', Factura_Proveedor_Detail_Imprimir.as_view(), name='Factura_Proveedor_Detail_Imprimir'),

    url(r'^Pedido-Eliminar/(?P<pk>[0-9]+)/$', Pedido_Eliminar.as_view(), name='Pedido_Eliminar'),
    url(r'^Factura-Eliminar/(?P<pk>[0-9]+)/$', Factura_Eliminar.as_view(), name='Factura_Eliminar'),
    url(r'^Factura-Modificar/(?P<pk>[0-9]+)/$', Factura_Modificar.as_view(), name='Factura_Modificar'),
]

Casa_Glamel/urls.py
from django.conf.urls import include, url
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('Apps.Inventario.urls', namespace='Inventario')),
    url(r'^', include('Apps.User.urls', namespace='User_app')),
    url(r'^', include('Apps.GestionInf.urls', namespace='Gestion')),
    url(r'^', include('Apps.ControlProv.urls', namespace='ControlProv')),
    url(r'^', include('Apps.Alquiler.urls', namespace='Alquiler')),
    url(r'^', include('Apps.ControlAdmin.urls', namespace='ControlAdmin')),
    url(r'^', include('Apps.Ventas.urls', namespace='VentasAdmin')),
    url(r'^',include('Apps.Reserva.urls', namespace='Reservas')),
    url(r'^',include('Apps.Egreso.urls', namespace='Egreso')),
    url(r'^',include('Apps.Notificaciones.urls', namespace='Notificaciones')),

]

templates/ModuloAdmin/ControlTemplate/factura_proveedor_detail.html
{% extends "base.html" %}
{% load static from staticfiles %}

{% block title %} Pedido {% endblock%}

{% block link%} <link href="{% static 'css/jquery.datatables.css' %}" rel="stylesheet">
 {%endblock%}

{% block user%}{{ user.username }}{% endblock %}

{% block user2 %}{{ user.username }}{% endblock %}

{% block page %} Pedido a proveedores {% endblock %}

{% block page2 %} Pedido a proveedores {% endblock %}

{% block contenido%}
     <div class="contentpanel">

      <div class="panel panel-default">
        <div class="panel-body">
            <div class="row">
                <div class="col-sm-4">
                    <img src="{% static 'images/descarga.png' %}" class="img-responsive mb10" alt=""
                            height="400" width="400"/>
                </div><!-- col-sm-6 -->

                <div class="col-sm-8">
                    <table style="width:100%">
                        {% for foo in pedido_proveedor %}
                        <tr>
                            <th>Factura No.</th>
                            <td>{{ factura_proveedor.pk }}</td>
                        </tr>
                        <tr>
                            <th>Empresa</th>
                            <td>{{ foo.nombre_Empresa}}</td>
                            <th>Nit.</th>
                            <td>{{  foo.nit }}</td>
                        </tr>
                            <tr>
                                <th>Direccion</th>
                                <td>{{ foo.direccion }}</td>
                            </tr>
                            <tr>
                                <th>Telefono</th>
                                <td>{{ foo.telefono }}</td>
                            </tr>
                            <tr>
                                <th>Fecha Pedido</th>
                                <td>{{ factura_proveedor.fecha_Pedido }}</td>
                                <th>Fecha Pago</th>
                                <td>{{ factura_proveedor.fecha_Pago }}</td>
                            </tr>
                        {% endfor %}
                    </table>
                </div>
            </div><!-- row -->
            <div class="table-responsive">
            <table class="table table-invoice">
            <thead>
              <tr>
                <th>Articulo</th>
                <th>Cantidad</th>
                <th>Unidad Precio</th>
                <th>Total Precio</th>
              </tr>
            </thead>
            <tbody>
            {% for pedido_detalle in pedido_detalle%}
              <tr>
                <td>
                    <div class="text-primary"><strong>{{ pedido_detalle.nombre_Articulo }}</strong></div>
                    <small>{{ pedido_detalle.descripcion }}</small>
                </td>
                <td>{{ pedido_detalle.cantidad }}</td>
                <td>{{ pedido_detalle.precio }}</td>
                <td>{{ cuentas.pop }}</td>
              </tr>
                {% endfor %}

          </table>
          </div><!-- table-responsive -->

            <table class="table table-total">
                <tbody>
                    <tr>
                        <td><strong>Sub Total :</strong></td>
                        <td>{{ suma }}</td>
                    </tr>
                    <tr>
                        <td><strong>TOTAL :</strong></td>
                        <td>{{ suma }}</td>
                    </tr>
                </tbody>
            </table>

            <div class="text-right btn-invoice">
                <button class="btn btn-primary mr5"><i class="fa fa-dollar mr5"></i> Generar Pago</button>
                <a href="{% url 'ControlProv:Factura_Proveedor_Detail_Imprimir'  factura_proveedor.pk %}" class="btn btn-white" target="_blank"><i class="fa fa-print mr5"></i> Imprimir</a>
            </div>

            <div class="mb40"></div>

            <div class="well">
                Thank you for your business. Please make sure all cheques payable to <strong>ThemeForest Web Services, Inc.</strong> Account No. 54353535
            </div>


        </div><!-- panel-body -->
      </div><!-- panel -->

    </div>
{% endblock %}

{% block linkscript %}{% endblock %}

{% block script %}
{% endblock %}

templates/ModuloAdmin/ControlTemplate/factura_proveedor_detail_imprimir.html
<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
  <meta name="description" content="">
  <meta name="author" content="">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Factura Proveedor</title>
  {% load static from staticfiles %}

  <link href="{%static 'css/style.default.css'%}" rel="stylesheet">
  
</head>
<div class="col-sm-3"></div>
<div class="contentpanel col-sm-6">
      <div class="panel panel-default">
        <div class="panel-body">
            <div class="row">
                <div class="row">
                <div class="col-sm-12">
                    <table style="width:100%">
                        {% for foo in pedido_proveedor %}
                        <tr>
                            <td rowspan="5">
                                <img src="{% static 'images/descarga.png' %}" class="img-responsive mb10" alt=""
                                height="200" width="200"/>
                            </td>
                            <th>Factura No.</th>
                            <td>{{ factura_proveedor.pk }}</td>
                        </tr>
                        <tr>
                            <th>Empresa:</th>
                            <td>{{ foo.nombre_Empresa}}</td>
                            <th>Nit.</th>
                            <td>{{  foo.nit }}</td>
                        </tr>
                            <tr>
                                <th>Direccion:</th>
                                <td colspan="3">{{ foo.direccion }}</td>
                            </tr>
                            <tr>
                                <th>Telefono:</th>
                                <td>{{ foo.telefono }}</td>
                                <th>Fecha Pedido:</th>
                                <td>{{ factura_proveedor.fecha_Pedido }}</td>
                            </tr>
                            <tr>
                                <th>Fecha Pago:</th>
                                <td>{{ factura_proveedor.fecha_Pago }}</td>
                            </tr>
                        {% endfor %}
                    </table>
                </div>
                </div><!-- row -->
            </div><!-- row -->
            <div>
            <table class="table table-invoice">
            <thead>
              <tr>
                <th>Articulo</th>
                <th>Cantidad</th>
                <th>Unidad Precio</th>
                <th>Total Precio</th>
              </tr>
            </thead>
            <tbody>
            {% for pedido_detalle in pedido_detalle%}
              <tr>
                <td>
                    <div class="text-primary"><strong>{{ pedido_detalle.nombre_Articulo }}</strong></div>
                    <small>{{ pedido_detalle.descripcion }}</small>
                </td>
                <td>{{ pedido_detalle.cantidad }}</td>
                <td>{{ pedido_detalle.precio }}</td>
                <td>{{ cuentas.pop }}</td>
              </tr>
              <tr>
                {% endfor %}
          </table>
          </div><!-- table-responsive -->
            <table class="table table-total">
                <tbody>
                    <tr>
                        <td><strong>Sub Total :</strong></td>
                        <td>{{ suma }}</td>
                    </tr>
                    <tr>
                        <td><strong>TOTAL :</strong></td>
                        <td>{{ suma }}</td>
                    </tr>
                </tbody>
            </table>
            <div class="mb40"></div>

            <div class="well">
                Thank you for your business. Please make sure all cheques payable to <strong>ThemeForest Web Services, Inc.</strong> Account No. 54353535
            </div>
        </div><!-- panel-body -->
      </div><!-- panel -->

    </div>
<body>


<script src="{%static 'js/jquery-1.10.2.min.js'%}"></script>
<script src="{%static 'js/jquery-migrate-1.2.1.min.js'%}"></script>
<script src="{%static 'js/bootstrap.min.js'%}"></script>
<script src="{%static 'js/modernizr.min.js'%}"></script>
<script src="{%static 'js/jquery.sparkline.min.js'%}"></script>
<script src="{%static 'js/toggles.min.js'%}"></script>
<script src="{%static 'js/retina.min.js'%}"></script>
<script src="{%static 'js/jquery.cookies.js'%}"></script>

<script src="{%static 'js/custom.js'%}"></script>

</body>
</html>

templates/ModuloAdmin/ControlTemplate/factura_proveedor_form.html
{% extends "base.html" %}
{% load static from staticfiles %}

{% block title %} Registro de Pedido {% endblock%}

{% block link%} {%endblock%}

{% block user%} {{ user.username }}{% endblock %}

{% block user2 %} {{ user.username }}{% endblock %}

{% block page %} Registro Proveedor {% endblock %}

{% block page2 %} Registro Proveedor {% endblock %}

{% block contenido%}
    <div class="col-md-12">
          <form id="basicForm" action="#" class="form-horizontal" method="POST">
          {% csrf_token %}
          <div class="panel panel-default">
              <div class="panel-heading">
                <div class="panel-btns">
                  <a href="#" class="panel-close">&times;</a>
                  <a href="#" class="minimize">&minus;</a>
                </div>
                <h4 class="panel-title">Proveedor</h4>
                <p>Bienvenido, por favor ingrese todos los datos</p>
              </div>
              <div class="panel-body">
                <div class="form-group">
                  <label class="col-sm-3 control-label">Nombre Proveedor<span class="asterisk">*</span></label>
                  <div class="col-sm-9">
                    {{ form.nombre_Empresa }}
                  </div>
                </div>
                <div class="form-group">
                  <label class="col-sm-3 control-label">Fecha Pedido <span class="asterisk">*</span></label>
                  <div class="col-sm-9">
                    {{ form.fecha_Pedido }}
                  </div>
                </div>
                <div class="form-group">
                  <label class="col-sm-3 control-label">Fecha de Pago<span class="asterisk">*</span></label>
                  <div class="col-sm-9">
                    {{ form.fecha_Pago }}
                  </div>
                </div>
                   <div class="form-group">
                  <label class="col-sm-3 control-label">Estado<span class="asterisk">*</span></label>
                  <div class="col-sm-9">
                      {{ form.estado }}
                  </div>
                </div>
              </div><!-- panel-body -->
              <div class="panel-footer">
                <div class="row">
                  <div class="col-sm-9 col-sm-offset-3">
                    <button class="btn btn-primary">Siguiente</button>
                    <button type="reset" class="btn btn-default">Reset</button>
                  </div>
                </div>
              </div>
          </div><!-- panel -->
          </form>
    </div>
{% endblock %}

{% block linkscript %}<script src="{% static 'js/jquery.validate.min.js'%}"></script>
    <script src="{% static 'js/jquery-ui-1.10.3.min.js'%}"></script>
{% endblock %}

{% block script %}
<script>
    jQuery(document).ready(function(){

      // Basic Form
      jQuery("#basicForm").validate({
        highlight: function(element) {
          jQuery(element).closest('.form-group').removeClass('has-success').addClass('has-error');
        },
        success: function(element) {
          jQuery(element).closest('.form-group').removeClass('has-error');
        }
      });


      // Validation with select boxes
      jQuery("#basicForm4").validate({
        highlight: function(element) {
          jQuery(element).closest('.form-group').removeClass('has-success').addClass('has-error');
        },
        success: function(element) {
          jQuery(element).closest('.form-group').removeClass('has-error');
        }
      });
        jQuery("#prueba").datepicker({dateFormat: 'dd/mm/yy'});
        jQuery('#prueba2').datepicker({dateFormat: 'dd/mm/yy'});


    });
</script>
{% endblock %}

templates/ModuloAdmin/ControlTemplate/factura_proveedor_list.html
{% extends "base.html" %}
{% load static from staticfiles %}

{% block title %} Proveedor {% endblock%}

{% block link%} <link href="{% static 'css/jquery.datatables.css' %}" rel="stylesheet"> {%endblock%}

{% block user%} {{ user.username }} {% endblock %}

{% block user2 %} {{ user.username }} {% endblock %}

{% block page %} Proveedor {% endblock %}

{% block page2 %} Proveedor {% endblock %}

{% block contenido%}
    <div class="panel panel-default">
        <div class="panel-heading">
          <div class="panel-btns">
            <a href="#" class="panel-close">&times;</a>
            <a href="#" class="minimize">&minus;</a>
          </div><!-- panel-btns -->
        </div>
        <div class="panel-body">
          <div class="table-responsive">
          <table class="table" id="table3">
              <thead>
                 <tr>
                    <th># Factura</th>
                    <th>Nombre Empresa</th>
                    <th>Fecha Pedido</th>
                    <th>Fecha de Pago</th>
                    <th>Estado</th>
                     <th></th>
                 </tr>
              </thead>
              <tbody>
                 {%for factura in factura%}
                 <tr class="odd gradeX">
                    <td>{{factura.pk}}</td>
                     <td>{{factura.nombre_Empresa}}</td>
                     <td>{{factura.fecha_Pedido}}</td>
                     <td>{{factura.fecha_Pago}}</td>
                     <td>{{factura.estado}}</td>
                    <td class="table-action">
                      <a href="{% url 'ControlProv:Factura_Proveedor_Detail' factura.pk %}">Ver mas</a>
                    </td>
                 </tr>

                 {%endfor%}
              </tbody>
           </table>
          </div><!-- table-responsive -->

        </div><!-- panel-body -->
      </div><!-- panel -->
{% endblock %}

{% block linkscript %}
<script src="{% static 'js/jquery.datatables.min.js'%}"></script>
<script src="{% static 'js/chosen.jquery.min.js'%}"></script>
{% endblock %}

{% block script %}
<script>
  jQuery(document).ready(function() {

    jQuery('#table').dataTable();

    jQuery('#table3').dataTable({
      "sPaginationType": "full_numbers"
    });

    // Chosen Select
    jQuery("select").chosen({
      'min-width': '100px',
      'white-space': 'nowrap',
      disable_search_threshold: 10
    });

    // Delete row in a table
    jQuery('.delete-row').click(function(){
      var c = confirm("Continue delete?");
      if(c)
        jQuery(this).closest('tr').fadeOut(function(){
          jQuery(this).remove();
        });

        return false;
    });

    // Show aciton upon row hover
    jQuery('.table-hidaction tbody tr').hover(function(){
      jQuery(this).find('.table-action-hide a').animate({opacity: 1});
    },function(){
      jQuery(this).find('.table-action-hide a').animate({opacity: 0});
    });
  });
</script>

{% endblock %}

templates/ModuloAdmin/ControlTemplate/pedido_form.html
{% extends "base.html" %}
{% load static from staticfiles %}

{% block title %} Pedido {% endblock%}

{% block link%} <link href="{% static 'css/jquery.datatables.css' %}" rel="stylesheet">
 {%endblock%}

{% block user%}{{ user.username }}{% endblock %}

{% block user2 %}{{ user.username }}{% endblock %}

{% block page %} Pedido a proveedores {% endblock %}

{% block page2 %} Pedido a proveedores {% endblock %}

{% block contenido%}
    <div class="col-md-12">
          <div class="panel panel-default">
              <div class="panel-heading">
                <div class="panel-btns">
                  <a href="#" class="panel-close">&times;</a>
                  <a href="#" class="minimize">&minus;</a>
                </div>
                  <div class="col-md-12">
                      <div class="table-responsive">
                      <table class="table  mb30">
                        <tbody>
                            <tr>
                                <td><strong>Factura:</strong> </td>
                                <td>{{ factura_proveedor.pk }}</td>
                                <td><strong>Fecha Pedido</strong></td>
                                <td>{{ factura_proveedor.fecha_Pedido }}</td>
                            </tr>
                            <tr>
                                <td><strong>Empresa Proveedora:</strong> </td>
                                <td>{{ factura_proveedor.nombre_Empresa }}</td>
                                <td></td>
                                <td></td>
                            </tr>
                            <tr>
                                <td><strong>Fecha de Pago:</strong> </td>
                                <td>{{ factura_proveedor.fecha_Pago }}</td>
                                <td><strong>Estado</strong></td>
                                <td>{{ factura_proveedor.estado }}</td>
                            </tr>
                        </tbody>
                      </table>
                      </div><!-- table-responsive -->
                    </div><!-- col-md-6 -->
                <h5>Bienvenido, por favor ingrese los articulos que va ha solicitar
                    <button class="btn btn-primary " data-toggle="modal" data-target="#myModal">
                            <i class="fa fa-plus-circle"></i>
                    </button>
                </h5>
              </div>
              <div class="panel-body">
                  <div class="col-md-12">
                      <div class="table-responsive">
                      <table class="table table-striped mb30">
                        <thead>
                          <tr>
                            <th>Cantidad</th>
                            <th>Nombre Articulo</th>
                            <th>Descripcion</th>
                            <th>Precio</th>
                          </tr>
                        </thead>
                        <tbody>
                        {% for pedido_detalle in pedido_detalle %}
                          <tr>
                            <td>{{ pedido_detalle.cantidad }}</td>
                            <td>{{ pedido_detalle.nombre_Articulo }}</td>
                            <td>{{ pedido_detalle.descripcion }}</td>
                            <td>{{ pedido_detalle.precio }}</td>
                          </tr>
                        {% endfor %}
                        </tbody>
                      </table>
                      </div><!-- table-responsive -->
                    </div><!-- col-md-6 -->
              </div><!-- panel-body -->
              <div class="panel-footer">
                <div class="row">
                  <div class="col-sm-9 col-sm-offset-3">
                    <a href="{% url 'ControlProv:Factura_Proveedor_Lista' %}" class="btn btn-primary">Confirmar</a>
                  </div>
                </div>
              </div>
          </div><!-- panel -->
    </div>

    <!-- Modal -->
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h4 class="modal-title" id="myModalLabel">Bienvenido <br><small>Ingrese todo los datos</small></h4>
          </div>
          <div class="modal-body">
            <form id="basicForm" action="#" class="form-horizontal" method="POST">
                {% csrf_token %}
                <div class="form-group">
                  <label class="col-sm-3 control-label">Cantidad<span class="asterisk">*</span></label>
                  <div class="col-sm-9">
                    {{ form.cantidad }}
                  </div>
                </div>
                <div class="form-group">
                  <label class="col-sm-3 control-label">Nombre Articulo<span class="asterisk">*</span></label>
                  <div class="col-sm-9">
                    {{ form.nombre_Articulo }}
                  </div>
                </div>
                <div class="form-group">
                  <label class="col-sm-3 control-label">Descripcion<span class="asterisk">*</span></label>
                  <div class="col-sm-9">
                    {{ form.descripcion }}
                  </div>
                </div>
                <div class="form-group">
                  <label class="col-sm-3 control-label">Precio<span class="asterisk">*</span></label>
                  <div class="col-sm-9">
                    {{ form.precio }}
                  </div>
                </div>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            <button type="submit" class="btn btn-primary">Agregar</button>
          </div></form>
        </div><!-- modal-content -->
      </div><!-- modal-dialog -->
    </div><!-- modal -->

{% endblock %}

{% block linkscript %}
    <script src="{% static 'js/jquery.datatables.min.js' %}"></script>
    <script src="{% static 'js/chosen.jquery.min.js' %}"></script>
 {% endblock %}

{% block script %}
<script>
  jQuery(document).ready(function() {

    jQuery('#table1').dataTable();

    jQuery('#table2').dataTable({
      "sPaginationType": "full_numbers"
    });

    // Chosen Select
    jQuery("select").chosen({
      'min-width': '100px',
      'white-space': 'nowrap',
      disable_search_threshold: 10
    });

    // Delete row in a table
    jQuery('.delete-row').click(function(){
      var c = confirm("Continue delete?");
      if(c)
        jQuery(this).closest('tr').fadeOut(function(){
          jQuery(this).remove();
        });

        return false;
    });

    // Show aciton upon row hover
    jQuery('.table-hidaction tbody tr').hover(function(){
      jQuery(this).find('.table-action-hide a').animate({opacity: 1});
    },function(){
      jQuery(this).find('.table-action-hide a').animate({opacity: 0});
    });


  });
</script>
{% endblock %}